In [22]:
import pandas as pd
import numpy as np
from tkinter import _flatten
import joblib
from sklearn.model_selection import train_test_split
from tqdm import tqdm
import benchmark_common as bcommon
import config as cfg
import os
import h5py
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
from sklearn.preprocessing import MultiLabelBinarizer
from keras.models import Model
from keras.optimizers import Adam
from keras.layers import Input, Dense
from keras.layers import GRU, Bidirectional
from tools import Attention
from tkinter import _flatten

In [96]:
data_task1_train = pd.read_feather(cfg.FILE_TASK1_TRAIN)
data_task2_train = pd.read_feather(cfg.FILE_TASK2_TRAIN)
data_task3_train = pd.read_feather(cfg.FILE_TASK3_TRAIN)

In [25]:
len(set(_flatten([ item.split(',') for item in  data_task3_train.ec_number.values])))

4854

In [114]:
data_task2_train

id                                                seq  \
0       P00958  MSFLISFDKSKKHPAHLQLANNLKIALALEYASKNLKPEVDNDNAA...   
1       P00812  METGPHYNYYKNRELSIVLAPFSGGQGKLGVEKGPKYMLKHGLQTS...   
2       P00959  MTQVAKKILVTCALPYANGSIHLGHMLEHIQADVWVRYQRMRGHEV...   
3       P00348  MAFATRQLVRSLSSSSTAAASAKKILVKHVTVIGGGLMGAGIAQVA...   
4       P00469  MLEQPYLDLAKKVLDEGHFKPDRTHTGTYSIFGHQMRFDLSKGFPL...   
...        ...                                                ...   
222562  Q8I6K2  MSNTAVLNDLVALYDRPTEPMFRVKAKKSFKVPKEYVTDRFKNVAV...   
222563  O81103  MATAPSPTTMGTYSSLISTNSFSTFLPNKSQLSLSGKSKHYVARRS...   
222564  Q21221  MSSGAPSGSSMSSTPGSPPPRAGGPNSVSFKDLCCLFCCPPFPSSI...   
222565  Q6QJ72  MSRLLLPKLFSISRTQVPAASLFNNLYRRHKRFVHWTSKMSTDSVR...   
222566  D9XDR8  MAKMSTTHEEIALAGPDGIPAVDLRDLIDAQLYMPFPFERNPHASE...   

        functionCounts  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1  
...                ...  
222562               1  
222563               1  
222564               1  
222565               1  
222566               1  

[222567 rows x 3 columns]

In [150]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
enc= preprocessing.OneHotEncoder(sparse=False)
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()

In [146]:
ak=enc.fit_transform([[item] for item in data_task1_train.isenzyme.to_list()])
ak

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [152]:
ak=enc.fit_transform([[item] for item in data_task2_train.functionCounts.to_list()])
ak

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [163]:
enc.inverse_transform([[0,0,0,0,0,1,0,0]])

array([[6]])

In [116]:
lb.fit_transform(data_task2_train.functionCounts.astype('int'))

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [108]:
label_list = data_task3_train.ec_number.to_list()
aa=mlb.fit_transform([ item.split(',') for item in label_list])
bb=mlb.transform([['1.-.-.-', '1.1.-.-', '6.6.1.2']])

cc=mlb.inverse_transform(bb)
print(bb)
print(cc)

[[1 1 0 ... 0 0 1]]
[('1.-.-.-', '1.1.-.-', '6.6.1.2')]


In [109]:
aa

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [107]:
label_list = data_task1_train.isenzyme.astype('int').to_list()
aa=mlb.fit_transform([label_list])
bb=mlb.transform([[0,1]])

cc=mlb.inverse_transform(bb)
print(bb)
print(cc)

[[1 1]]
[(0, 1)]


In [104]:
mlb.classes_

array([0, 1])

In [99]:
label_list

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 

In [97]:
data_task1_train

id                                                seq  isenzyme
0       Q3J1A3  MADKSDLGYTGLTDEQAQELHSVYMSGLWLFSAVAIVAHLAVYIWRPWF     False
1       P02157  MGLSDGEWQLVLNVWGKVEADLAGHGQEVLIRLFKGHPETLEKFDK...     False
2       P02178  MVLSDAEWQLVLNIWAKVEADVAGHGQDILIRLFKGHPETLEKFDK...     False
3       P02194  MGLSDGEWQLVLNIWGKVETDEGGHGKDVLIRLFKGHPETLEKFDK...     False
4       P01915  MVWLPRVPCVAAVILLLTVLSPPVALVRDTRPRFLEYVTSECHFYN...     False
...        ...                                                ...       ...
469129  Q21221  MSSGAPSGSSMSSTPGSPPPRAGGPNSVSFKDLCCLFCCPPFPSSI...      True
469130  Q6QJ72  MSRLLLPKLFSISRTQVPAASLFNNLYRRHKRFVHWTSKMSTDSVR...      True
469131  C0HL68     GLFSKPAGKGIKNLIPKGVKHIGKEVGKDVIRTGIDVAGCKIKGEC     False
469132  C0HK74  GSICLEPKVVGPCTAYFPRFYFDSETGKCTPFIYGGCEGNGNNFET...     False
469133  D9XDR8  MAKMSTTHEEIALAGPDGIPAVDLRDLIDAQLYMPFPFERNPHASE...      True

[469134 rows x 3 columns]

In [33]:
label_list = data_task3_train.ec_number.to_list()

encoder_onehot = preprocessing.OneHotEncoder()
encoder_label = preprocessing.LabelEncoder()
lb_encoded = encoder_label.fit_transform(list(set(_flatten([ item.split(',') for item in label_list]))))
encoder_onehot.fit(lb_encoded.reshape(-1,1))
onehot_encoded_lb = encoder_onehot.transform(encoder_label.transform(label_list).reshape(-1, 1))

# if save ==True:
#     joblib.dump(encoder_onehot, file_enc_onehot)
#     joblib.dump(encoder_label, file_enc_lb)

onehot_encoded_lb.A


ValueError: bad input shape (1, 2)

In [12]:
pd.DataFrame(onehot_encoded_lb.A)

0     1     2     3     4     5     6     7     8     9     ...  5408  \
0        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
222562   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
222563   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
222564   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
222565   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
222566   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

        5409  5410  5411  5412  5413  5414  5415  5416  5417  
0        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4        0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
...      ...   ...   ...   ...   ...   ...   ...   ...   ...  
222562   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
222563   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
222564   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
222565   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
222566   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[222567 rows x 5418 columns]

In [58]:
def make_onehot_label(label_list, save=True, file_enc_lb='', file_enc_onehot=''):
    encoder_onehot = preprocessing.OneHotEncoder()
    encoder_label = preprocessing.LabelEncoder()
    lb_encoded = encoder_label.fit_transform(label_list)
    encoder_onehot.fit(lb_encoded.reshape(-1,1))
    onehot_encoded_lb = encoder_onehot.transform(encoder_label.transform(label_list).reshape(-1, 1))

    if save ==True:
        joblib.dump(encoder_onehot, file_enc_onehot)
        joblib.dump(encoder_label, file_enc_lb)

    return onehot_encoded_lb.A
    

make_onehot_label(label_list=['a','c','d'], file_enc_lb='task1_lbenc_lb.h5', file_enc_onehot='task1_lbenc_onehot.h5')

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
enc = OneHotEncoder()
lb = LabelEncoder()
tmp = lb.fit_transform([123,456,789])
print(tmp)#输出LabelEncoder的结果
enc.fit(tmp.reshape(-1,1))#将LabelEncoder的结果作为OneHotEncoder特征输入
x_train = enc.transform(lb.transform([123,789]).reshape(-1, 1))
#输出特征[123,789]的OneHotEncoder的编码结果


[0 1 2]
  (0, 0)	1.0
  (1, 2)	1.0


In [48]:
               #关闭文件

In [34]:
lb.inverse_transform(enc.inverse_transform(x_train).ravel())

array([123, 789])

In [37]:
joblib.dump(lb,'aa.h5')

['aa.h5']

In [38]:
kk=joblib.load('aa.h5')

In [40]:
kk.inverse_transform(enc.inverse_transform(x_train).ravel())

array([123, 789])

In [27]:
np.array(x_train.A)

array([[1., 0., 0.],
       [0., 0., 1.]])

In [6]:
le.transform([1, 1, 2, 6])

array([0, 0, 1, 2])

In [7]:
le.inverse_transform([0, 0, 1, 2])

array([1, 1, 2, 6])

In [ ]:
LabelEncoder()
le.classes_
array([1, 2, 6])
le.transform([1, 1, 2, 6])
array([0, 0, 1, 2])
le.inverse_transform([0, 0, 1, 2])
array([1, 1, 2, 6])

In [3]:
#region
def get_train_X_Y(traindata, feature_bankfile, task=1, task3_test=None):
    
    traindata = traindata.merge(feature_bankfile, on='id', how='left')
    return traindata
#endregion



#region 获取EC号训练的数据集
def get_ec_train_set(train_data, ec_label_dict):
    """[获取EC号训练的数据集]
    Args:
        ec_label_dict: ([dict]): [ec to label dict]
        train_data ([DataFrame]): [description]
    Returns:
        [DataFrame]: [[train_x, trian_y]]
    """
    if cfg.TRAIN_USE_ONLY_ENZYME:
        train_data = train_data[train_data.isemzyme] #仅选用酶数据
    # if cfg.TRAIN_USE_ONLY_SINGLE_FUNCTION:
    train_data = train_data[train_data.functionCounts ==1] #仅选用单功能酶数据
    
    train_data = train_data[(train_data.ec_specific_level >= cfg.TRAIN_USE_SPCIFIC_EC_LEVEL) |(train_data.ec_specific_level ==0)]
    train_data.reset_index(drop=True, inplace=True)
    train_data.insert(loc=1, column='ec_label', value=train_data.ec_number.apply(lambda x: ec_label_dict.get(x)))
    # train_data['ec_label'] = train_data.ec_number.apply(lambda x: ec_label_dict.get(x))

    train_X = train_data.iloc[:, 8:]
    train_Y =train_data['ec_label']
    return train_X, pd.DataFrame(train_Y)

#endregion

#region 训练是否是酶模型
def train_isenzyme(x_train,y_train,x_vali,y_vali,ecs, model_file,force_model_update=False):
    """[训练是否是酶模型]

    Args:
        vali_ratio:
        X ([DataFrame]): [特征数据]
        Y ([DataFrame]): [标签数据]
        model_file ([string]): [模型的存放路径]
        force_model_update (bool, optional): [是否强制更新模型]. Defaults to False.

    Returns:
        [object]: [训练好的模型]
    """
    if os.path.exists(model_file) and (force_model_update==False):
        return
    else:
        # 模型设置，训练，保存
        inputs = Input(shape=(1,x_train.shape[2]), name="input")
        gru = Bidirectional(GRU(512, dropout=0.2, return_sequences=True), name="bi-gru")(inputs)
        attention = Attention.Attention(32)(gru)
        num_class = len(ecs)
        output = Dense(num_class, activation='sigmoid', name="dense")(attention)
        model = Model(inputs, output)

        model.compile(loss='binary_crossentropy',optimizer=Adam(),metrics=['accuracy'])
        model.fit(x_train, y_train, validation_data=(x_vali,y_vali), batch_size=512, epochs= 400)
        # 保存
        model.save(model_file)
        print('gru+attention模型训练完成')
        return model
#endregion

#region 构建几功能酶模型
def train_howmany_enzyme(x_train,y_train,x_vali,y_vali,ecs, model_file,force_model_update=False):
    """[构建几功能酶模型]

    Args:
        force_model_update:
        vali_ratio:
        model_file:
        data_x ([DataFrame]): [X训练数据]
        data_y ([DataFrame]): [Y训练数据]

    Returns:
        [object]: [训练好的模型]
    """
    if os.path.exists(model_file) and (force_model_update==False):
        return
    else:
        # 模型设置，训练，保存
        inputs = Input(shape=(1,x_train.shape[2]), name="input")
        gru = Bidirectional(GRU(512, dropout=0.2, return_sequences=True), name="bi-gru")(inputs)
        attention = Attention.Attention(32)(gru)
        num_class = len(ecs)
        output = Dense(num_class, activation='sigmoid', name="dense")(attention)
        model = Model(inputs, output)

        model.compile(loss='binary_crossentropy',
                    optimizer=Adam(),
                    metrics=['accuracy'])
        model.fit(x_train, y_train, validation_data=(x_vali,y_vali),batch_size=512, epochs= 1)
        # 保存
        model.save(model_file)
        print('gru+attention模型训练完成')
        return model
#endregion


def make_ec_label_dict(ec_str_list, file_save=cfg.FILE_EC_LABEL_DICT):
    if os.path.exists(file_save):
        print(f'ec label dict already exist, using existing file:{cfg.FILE_EC_LABEL_DICT}')
        dict_ec_label = np.load(cfg.FILE_EC_LABEL_DICT, allow_pickle=True).item()
        return dict_ec_label

    ecs = _flatten([item.split(',') for item in ec_str_list])
    ecs = list(set(ecs))
    ec_label_dict = {k: v for k, v in zip(ecs, range(len(ecs)))}
    np.save(file_save, ec_label_dict)
    return  ec_label_dict
    print('字典保存成功')


#region 训练slice模型
def train_ec_gru(x_train,y_train,x_vali,y_vali,ecs, model_file,force_model_update=False):
    """[训练slice模型]
    Args:
        trainX ([DataFarame]): [X特征]
        trainY ([DataFrame]): [ Y标签]]
        modelPath ([string]): [存放模型的目录]
        force_model_update (bool, optional): [是否强制更新模型]. Defaults to False.
    """
    if os.path.exists(model_file) and (force_model_update==False):
        return
    else:
        # 模型设置，训练，保存
        inputs = Input(shape=(1,x_train.shape[2]), name="input")
        gru = Bidirectional(GRU(512, dropout=0.2, return_sequences=True), name="bi-gru")(inputs)
        attention = Attention.Attention(32)(gru)
        num_class = len(ecs)
        output = Dense(num_class, activation='sigmoid', name="dense")(attention)
        model = Model(inputs, output)

        model.compile(loss='binary_crossentropy',
                    optimizer=Adam(),
                    metrics=['accuracy'])
        model.fit(x_train, y_train, validation_data=(x_vali,y_vali),batch_size=3948, epochs= 400)
        # 保存
        model.save(model_file)
        return model
#endregion

#region 数据处理
def data_process(dataset, task=1,vali_ratio=0.3):
    labe = 'isenzyme'
    x_train, x_vali = train_test_split(dataset,test_size=vali_ratio,random_state=1)

    if task == 1:
        label = 'isenzyme'
    elif task == 2:
        label = 'functionCounts'
    else:
        label = 'ec_number'
    
    ecs= (set(dataset[label]))
    label_dict = dict(zip(set(ecs), range(len(ecs))))
    def get_label(ecnum_str):
        label_init = np.zeros(len(label_dict),  dtype=int)
        label_init[label_dict.get(ecnum_str)] = 1
        return list(label_init)
    train_label = x_train[label].apply(lambda x: get_label(ecnum_str=x))
    train_label=[item for item in train_label]

    vali_label = x_vali[label].apply(lambda x: get_label(ecnum_str=x))
    vali_label=[item for item in vali_label]

    y_train = np.array(train_label)
    y_vali = np.array(vali_label)

    x_train = x_train.iloc[:,3:]
    x_train = np.array(x_train)
    x_train =np.reshape(x_train,(x_train.shape[0],1,x_train.shape[1]))

    x_vali = x_vali.iloc[:,3:]
    x_vali = np.array(x_vali)
    x_vali =np.reshape(x_vali,(x_vali.shape[0],1,x_vali.shape[1]))
    
    return x_train,y_train,x_vali,y_vali,ecs

#endregion


In [4]:
def labelsave(ecs,labefile):
    fileObject = open(labefile, 'w')  
    for ip in ecs:  
        fileObject.write(str(ip))  
        fileObject.write('\n') 
    fileObject.close() 



In [5]:
EMBEDDING_METHOD = 'esm32'

# 1. 读入数据
print('step 1 loading task data')
data_task1_train = pd.read_feather(cfg.FILE_TASK1_TRAIN)
data_task2_train = pd.read_feather(cfg.FILE_TASK2_TRAIN)
data_task3_train = pd.read_feather(cfg.FILE_TASK3_TRAIN)
data_task3_test = pd.read_feather(cfg.FILE_TASK3_TEST_2019)

# # 2. 读取特征
print(f'step 2: Loading features, embdding method={EMBEDDING_METHOD}')
feature_df = bcommon.load_data_embedding(embedding_type=EMBEDDING_METHOD)

#3. task1 train
print('step 3: train isEnzyme model')
task1_X = get_train_X_Y(traindata=data_task1_train, feature_bankfile=feature_df, task=1)
task1_X = task1_X.iloc[:100,:]
x_train,y_train,x_vali,y_vali,ecs = data_process(task1_X,1)

step 1 loading task data
step 2: Loading features, embdding method=esm32
step 3: train isEnzyme model


In [6]:
x_train.shape

(70, 1, 1280)

In [14]:
y_train

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [13]:
train_isenzyme(x_train,y_train,x_vali,y_vali,ecs,model_file=cfg.ISENZYME_MODEL, force_model_update=cfg.UPDATE_MODEL)

2023-02-02 12:24:09.411750: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 24061 MB memory:  -> device: 0, name: NVIDIA RTX A6000, pci bus id: 0000:37:00.0, compute capability: 8.6


Epoch 1/400


2023-02-02 12:24:13.978446: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:428] Loaded cuDNN version 8401
2023-02-02 12:24:14.142700: I tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:630] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.


1/1 [==============================] - 4s 4s/step - loss: 0.6876 - accuracy: 0.6000 - val_loss: 0.1584 - val_accuracy: 1.0000
Epoch 2/400
1/1 [==============================] - 0s 34ms/step - loss: 0.1667 - accuracy: 1.0000 - val_loss: 0.0370 - val_accuracy: 1.0000
Epoch 3/400
1/1 [==============================] - 0s 39ms/step - loss: 0.0415 - accuracy: 1.0000 - val_loss: 0.0104 - val_accuracy: 1.0000
Epoch 4/400
1/1 [==============================] - 0s 38ms/step - loss: 0.0132 - accuracy: 1.0000 - val_loss: 0.0034 - val_accuracy: 1.0000
Epoch 5/400
1/1 [==============================] - 0s 36ms/step - loss: 0.0051 - accuracy: 1.0000 - val_loss: 0.0013 - val_accuracy: 1.0000
Epoch 6/400
1/1 [==============================] - 0s 35ms/step - loss: 0.0023 - accuracy: 1.0000 - val_loss: 5.7218e-04 - val_accuracy: 1.0000
Epoch 7/400
1/1 [==============================] - 0s 35ms/step - loss: 0.0012 - accuracy: 1.0000 - val_loss: 2.7300e-04 - val_accuracy: 1.0000
Epoch 8/400
1/1 [=========

In [5]:
if __name__ =="__main__":
    
    EMBEDDING_METHOD = 'esm32'

    # 1. 读入数据
    print('step 1 loading task data')
    data_task1_train = pd.read_feather(cfg.FILE_TASK1_TRAIN)
    data_task2_train = pd.read_feather(cfg.FILE_TASK2_TRAIN)
    data_task3_train = pd.read_feather(cfg.FILE_TASK3_TRAIN)
    data_task3_test = pd.read_feather(cfg.FILE_TASK3_TEST_2019)

    # # 2. 读取特征
    print(f'step 2: Loading features, embdding method={EMBEDDING_METHOD}')
    feature_df = bcommon.load_data_embedding(embedding_type=EMBEDDING_METHOD)

    #3. task1 train
    print('step 3: train isEnzyme model')
    task1_X = get_train_X_Y(traindata=data_task1_train, feature_bankfile=feature_df, task=1)
    task1_X = task1_X.iloc[:100,:]
    x_train,y_train,x_vali,y_vali,ecs = data_process(task1_X,1)
    labelsave(ecs,labefile=cfg.ISENZYME_LABEL)
    train_isenzyme(x_train,y_train,x_vali,y_vali,ecs,model_file=cfg.ISENZYME_MODEL, force_model_update=cfg.UPDATE_MODEL)


    #4. task2 train
    print('step 4: train how many enzymes model')
    task2_X= get_train_X_Y(traindata=data_task2_train, feature_bankfile=feature_df, task=2)
    task2_X = task2_X.iloc[:100,:]
    x_train,y_train,x_vali,y_vali,ecs = data_process(task2_X,2)
    labelsave(ecs,labefile=cfg.HOWMANY_LABEL)
    train_howmany_enzyme(x_train,y_train,x_vali,y_vali,ecs,model_file=cfg.HOWMANY_MODEL, force_model_update=cfg.UPDATE_MODEL)


    #4. 加载EC号训练数据
    print('step 5:loading ec to label dict')
    task3_X = get_train_X_Y(traindata=data_task3_train, feature_bankfile=feature_df, task=3, task3_test=data_task3_test)
    task3_X = task3_X.iloc[:100,:]
    x_train,y_train,x_vali,y_vali,ecs = data_process(task3_X,3)
    labelsave(ecs,labefile=cfg.EC_LABEL)
    train_ec_gru(x_train,y_train,x_vali,y_vali,ecs,model_file=cfg.EC_MODEL, force_model_update=cfg.UPDATE_MODEL)
    

    # # 2. 写入fasta文件

    # table2fasta(table=train,file_out=cfg.TRAIN_FASTA)
    # table2fasta(table=test, file_out=cfg.TEST_FASTA)
    # #7. 创建blast比对数据库
    # bcommon.make_diamond_db(dbtable=train.iloc[:, np.r_[0,5]],to_db_file=cfg.FILE_BLAST_TRAIN_DB) # 创建是否是酶blast数据库

    print('train finished')

step 1 loading task data
step 2: Loading features, embdding method=esm32
step 3: train isEnzyme model


AttributeError: module 'config' has no attribute 'ISENZYME_LABEL'